#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "SDL/SDL.h"
#include "SDL/SDL_image.h"
#include "SDL/SDL_ttf.h"

/*
  WARRIOR
 */
#define WARRIOR_HP 700
#define WARRIOR_DAMAGE 100

/*
  BOW ARROW ARCHER
 */
#define ARROW_HP 600
#define ARROW_DAMAGE 100

/*
  WIZARD
 */
#define WIZARD_HP 500
#define WIZARD_DAMAGE 100


#define MAX_BATTLES 10

/* GAME INTEFACE DEFINITIONS */

#define MAX_SPRITES 30

enum
{
	BACKGROUND,
	MAIN_MENU_ITEM1,
	MAIN_MENU_ITEM2,
	MAIN_MENU_ITEM3,
	MAIN_MENU_ITEM1_SELECTED,
	MAIN_MENU_ITEM2_SELECTED,
	MAIN_MENU_ITEM3_SELECTED,
	BACKGROUND_CHOOSE_MENU,
	CHOOSE_MENU_ITEM1,
	CHOOSE_MENU_ITEM2,
	CHOOSE_MENU_ITEM3,
	CHOOSE_MENU_ITEM_SELECTED,
	BACKGROUND_BATTLE,
	LIFE_0,
	LIFE_10,
	LIFE_20,
	LIFE_30,
	LIFE_40,
	LIFE_50,
	LIFE_60,
	LIFE_70,
	LIFE_80,
	LIFE_90,
	LIFE_100,
	PLAYER_WIZARD,
	PLAYER_ARCHER,
	PLAYER_WARRIOR,
	ENEMY_WIZARD,
	ENEMY_ARCHER,
	ENEMY_WARRIOR
};